### ISSUE TITLE
Add suport for context-parameter

### ISSUE THREAD

**Issue by nknapp** [nknapp/gql2ts-for-server#16]
The `context`-parameter (used for [authorization](http://graphql.org/learn/authorization/)) is passed by graphql into function-style properties. Functions generated in the TypeScript interfaces should have that parameter as well.

I have not found an official spec yet, but I have tried with a debugger. This is essential for creating applications that use authentation/authorization.

**Comment by nknapp** [comment]
Actually, it's in [this example](http://graphql.org/learn/execution/#root-fields-resolvers)

**Comment by msiegenthaler** [comment]
I've had problems with arguments to the query.. the example you linked to specifies the call signature as:
`myQuery(obj, args, context)`

currently we are generating:
`myQuery(args: {myArg: string})`

actually I think we generate:
`myQuery(obj: any, args: {myArg: string}, context: any)`

would you agree if I changed the generated function to look like this?
Actually it'd be nice if `context` had a 'real' type.. I could try making it configurable (maybe not over the CLI, but at least internal).

**Comment by nknapp** [comment]
I have  to look into that more closely. In the end, the generated interfaces should reflect the code that is needed to be written.

Currently, I don't understand how there can be two different incompatible alternatives of method signatures. After all, graqhql has to call them. Which version does it use?

I noticed that yesterday evening, but did not have the chance to comment yet.
I don't know if I can do this in the evening. Probably not before tommorrow evening.

**Comment by msiegenthaler** [comment]
yes, of course, they should match the signature as called by graphql.
I reviewed the docs again and found that unfortunately Apollo and graphql-js differ in their handling: 

- Apollo Server: http://graphql.org/learn/execution/#root-fields-resolvers => (root, arg, context)
- graphql-js: http://graphql.org/graphql-js/passing-arguments/ => (arg, request)

The example you linked to actually uses the Apollo syntax, that got me confused.

**Comment by msiegenthaler** [comment]
I propose to add a setting so we can support both, Apollo and graphql-js, I'll do so in #22

**Comment by nknapp** [comment]
I don't know where this is documented, but this example works:

```typescript
import {graphql, buildSchema} from 'graphql'
import {schema} from './graphql/schema/example.graphqls'
import * as fs from 'fs'

// Implement the generated interface
class Root implements schema.Query {
    person(args: {name: string}): schema.Person|Promise<schema.Person> {
        return new Person(args.name, 1979)
    }
}

class Person implements schema.Person {
    name: string
    yearOfBirth: number

    constructor(name: string, yearOfBirth: number) {
        this.name = name
        this.yearOfBirth = yearOfBirth
    }

    age(): number {
        return arguments[1].year - this.yearOfBirth
    }

    async friends(): Promise<Person[]> {
        console.log('arguments', arguments)
        return Promise.resolve([
            new Person(this.name + "'s first friend", this.yearOfBirth + 1),
            new Person(this.name + "'s second friend", this.yearOfBirth + 2)
        ])
    }
}

// Run a query
graphql(
    buildSchema(fs.readFileSync('graphql/schema/example.graphqls', {encoding: 'utf-8'})),
    '{ person(name:"Joye") { name age friends { name age } }}',
    new Root(),
    { year: 2017 }
).then((result) => console.log(JSON.stringify(result, null, 2)))
```
It passes the object `{ year: 2017}` as context (as third parameter to the `graphql`-function). It does not have to be a request.

**Comment by msiegenthaler** [comment]
Great, will you update the example?

Are you ok with me adding an Apollo variant? It would be very helpful since I use Apollo.

**Comment by nknapp** [comment]
Sure, go ahead. This would be a CLI-parameter then?

**Comment by msiegenthaler** [comment]
yep

**Comment by nknapp** [comment]
The context could be a generic to the generated interfaces, like: 

```typescript
export namespace schema {
    /**
     * The base query
     */
    export interface Query<C> {
        /**
         * Retrieve a person by name
         */
        person(args: {name: string}, context: C): Person<C> | Promise<Person<C>>
    }

    /**
     * A type describing a person
     */
    export interface Person<C> {
        /**
         * The persons name
         */
        name: string | Promise<string> | { (args: {}, context: C): string } | { (args: {}, context: C): Promise<string> }
        /**
         * The persons age in years
         */
        age: number | Promise<number> | { (args: {}, context: C): number } | { (args: {}, context: C): Promise<number> }
        /**
         * Friendship relations to other persons
         */
        friends: Person<C>[] | Promise<Person<C>[]> | { (): Person<C>[] } | { (): Promise<Person<C>[]> }
    }
}
```

**Comment by nknapp** [comment]
Updating the example only makes sense once the feature is implemented. The example is run when the README is generated, and the output is the actual console-output of the execution. 
I cannot commit an example that would not compile... But I can do this later, yeah.

**Comment by nknapp** [comment]
Oh, and: When I added this issue, I didn't mean to tell you to implement it. I just did not want it to be forgotten. But it's fine if you want to do that. It feels like you already put more work into this project than I did.

**Comment by msiegenthaler** [comment]
I did not take it as an "order" to implement it :) It just happened that I needed it as well..

**Comment by msiegenthaler** [comment]
I actually updated the example to yours above, so I'm closing the issue - Context parameters are now supported.
