### ISSUE TITLE
Is the reverse operation possible?

### ISSUE THREAD

**Issue by azaslavsky** [nknapp/gql2ts-for-server#38]
Would it be possible to convert GraphQL types to TypeScript with this library?

**Comment by nknapp** [comment]
Yes, that is the purpose of this library. Take some GraphQL-schema files and generate TypeScript-interfaces.

**Comment by azaslavsky** [comment]
Stupid mistake on my part (it was a long day...).  I meant is it possible to convert this script definitions to Graphql types?

**Comment by nknapp** [comment]
No. That's not possible.
