### ISSUE TITLE
Honour "tslint.json" when generating output

### ISSUE THREAD

**Issue by nknapp** [nknapp/gql2ts-for-server#8]
The generated interfaces should be created according to the style-rules of a local "tslint.json" file. 
I would suggest changing the renderer into a real class with tslint-options provided in the constructor.

This should control things such as:

* Adding semicolon at the end of the line
* Amount of indent within blocks (interfaces)

**Comment by msiegenthaler** [comment]
#12 does at least tell tslint to ignore the generated file. I think for most cases this is good enough.

**Comment by nknapp** [comment]
I think that is good enough, thanks
